CUSTOMER_ORDERS = [
    {
        "name": "Office Build",
        "budget": 750,
        "required_gpu": "GTX 1650",
        "required_cpu": "Core i3-12100 (LGA1700)",
        "required_ram": "8GB DDR4",
        "required_storage": "500GB SATA SSD",
        "reward_multiplier": 0.3,
        "min_rep": 0,
    },
    {
        "name": "Budget Gamer",
        "budget": 950,
        "required_gpu": "RX 6600",
        "required_cpu": "Ryzen 5 5500 (AM4)",
        "required_ram": "16GB DDR4",
        "required_storage": "1TB NVMe Gen3",
        "reward_multiplier": 0.4,
        "min_rep": 0,
    },
    {
        "name": "Affordable Gaming",
        "budget": 1250,
        "required_gpu": "RTX 3060",
        "required_cpu": "Ryzen 5 5600X (AM4)",
        "required_ram": "16GB DDR4",
        "required_storage": "1TB NVMe Gen3",
        "reward_multiplier": 0.45,
        "min_rep": 20,
    },
    {
        "name": "Streaming Workstation",
        "budget": 1600,
        "required_gpu": "RTX 4060 Ti",
        "required_cpu": "Core i5-13400 (LGA1700)",
        "required_ram": "32GB DDR4",
        "required_storage": "1TB NVMe Gen4",
        "reward_multiplier": 0.5,
        "min_rep": 40,
    },
    {
        "name": "High-End Gaming",
        "budget": 2500,
        "required_gpu": "RTX 4070 Super",
        "required_cpu": "Ryzen 7 7800X3D (AM5)",
        "required_ram": "32GB DDR5",
        "required_storage": "2TB NVMe Gen4",
        "reward_multiplier": 0.6,
        "min_rep": 60,
    },
    {
        "name": "Enthusiast Build",
        "budget": 4300,
        "required_gpu": "RTX 4090",
        "required_cpu": "Core i9-14900K (LGA1700)",
        "required_ram": "64GB DDR5",
        "required_storage": "2TB NVMe Gen4",
        "reward_multiplier": 0.8,
        "min_rep": 80,
    },
]

PARTS_ITEMS = [
    {
        "name": "Core i3-12100 (LGA1700)",
        "price": 110,
        "type": "CPU",
        "socket": "LGA1700",
        "watt": 89,
    },
    {
        "name": "Core i5-13400 (LGA1700)",
        "price": 220,
        "type": "CPU",
        "socket": "LGA1700",
        "watt": 154,
    },
    {
        "name": "Core i7-14700K (LGA1700)",
        "price": 400,
        "type": "CPU",
        "socket": "LGA1700",
        "watt": 253,
    },
    {
        "name": "Core i9-14900K (LGA1700)",
        "price": 580,
        "type": "CPU",
        "socket": "LGA1700",
        "watt": 300,
    },
    {
        "name": "Ryzen 5 5500 (AM4)",
        "price": 90,
        "type": "CPU",
        "socket": "AM4",
        "watt": 65,
    },
    {
        "name": "Ryzen 5 5600X (AM4)",
        "price": 150,
        "type": "CPU",
        "socket": "AM4",
        "watt": 76,
    },
    {
        "name": "Ryzen 7 5800X3D (AM4)",
        "price": 320,
        "type": "CPU",
        "socket": "AM4",
        "watt": 142,
    },
    {
        "name": "Ryzen 5 7600 (AM5)",
        "price": 220,
        "type": "CPU",
        "socket": "AM5",
        "watt": 88,
    },
    {
        "name": "Ryzen 7 7800X3D (AM5)",
        "price": 400,
        "type": "CPU",
        "socket": "AM5",
        "watt": 162,
    },
    {
        "name": "Ryzen 9 7950X (AM5)",
        "price": 550,
        "type": "CPU",
        "socket": "AM5",
        "watt": 230,
    },
    {
        "name": "H610M DDR4 (LGA1700)",
        "price": 80,
        "type": "MB",
        "socket": "LGA1700",
        "watt": 30,
        "ram_type": "DDR4",
    },
    {
        "name": "B760M DDR4 (LGA1700)",
        "price": 130,
        "type": "MB",
        "socket": "LGA1700",
        "watt": 35,
        "ram_type": "DDR4",
    },
    {
        "name": "B760 Pro DDR5 (LGA1700)",
        "price": 160,
        "type": "MB",
        "socket": "LGA1700",
        "watt": 35,
        "ram_type": "DDR5",
    },
    {
        "name": "Z790 Elite DDR5 (LGA1700)",
        "price": 250,
        "type": "MB",
        "socket": "LGA1700",
        "watt": 40,
        "ram_type": "DDR5",
    },
    {
        "name": "A520M DDR4 (AM4)",
        "price": 70,
        "type": "MB",
        "socket": "AM4",
        "watt": 30,
        "ram_type": "DDR4",
    },
    {
        "name": "B550 Steel Legend DDR4 (AM4)",
        "price": 130,
        "type": "MB",
        "socket": "AM4",
        "watt": 35,
        "ram_type": "DDR4",
    },
    {
        "name": "A620M DDR5 (AM5)",
        "price": 100,
        "type": "MB",
        "socket": "AM5",
        "watt": 30,
        "ram_type": "DDR5",
    },
    {
        "name": "B650 Gaming DDR5 (AM5)",
        "price": 180,
        "type": "MB",
        "socket": "AM5",
        "watt": 35,
        "ram_type": "DDR5",
    },
    {
        "name": "X670E Taichi DDR5 (AM5)",
        "price": 350,
        "type": "MB",
        "socket": "AM5",
        "watt": 40,
        "ram_type": "DDR5",
    },
    {"name": "GTX 1650", "price": 150, "type": "GPU", "watt": 75},
    {"name": "RTX 3060", "price": 280, "type": "GPU", "watt": 170},
    {"name": "RTX 4060 Ti", "price": 380, "type": "GPU", "watt": 160},
    {"name": "RTX 4070 Super", "price": 600, "type": "GPU", "watt": 220},
    {"name": "RTX 4080 Super", "price": 1000, "type": "GPU", "watt": 320},
    {"name": "RTX 4090", "price": 1800, "type": "GPU", "watt": 450},
    {"name": "RX 6600", "price": 200, "type": "GPU", "watt": 132},
    {"name": "RX 7800 XT", "price": 500, "type": "GPU", "watt": 263},
    {"name": "8GB DDR4", "price": 25, "type": "RAM", "watt": 5, "ram_type": "DDR4"},
    {"name": "16GB DDR4", "price": 45, "type": "RAM", "watt": 10, "ram_type": "DDR4"},
    {"name": "32GB DDR4", "price": 70, "type": "RAM", "watt": 15, "ram_type": "DDR4"},
    {"name": "16GB DDR5", "price": 60, "type": "RAM", "watt": 10, "ram_type": "DDR5"},
    {"name": "32GB DDR5", "price": 100, "type": "RAM", "watt": 15, "ram_type": "DDR5"},
    {"name": "64GB DDR5", "price": 200, "type": "RAM", "watt": 25, "ram_type": "DDR5"},
    {"name": "500GB SATA SSD", "price": 35, "type": "Storage", "watt": 5},
    {"name": "1TB NVMe Gen3", "price": 60, "type": "Storage", "watt": 8},
    {"name": "1TB NVMe Gen4", "price": 90, "type": "Storage", "watt": 10},
    {"name": "2TB NVMe Gen4", "price": 160, "type": "Storage", "watt": 10},
    {"name": "Standard Office Case", "price": 30, "type": "Case", "watt": 0},
    {"name": "Budget Mesh Case", "price": 50, "type": "Case", "watt": 0},
    {"name": "Premium ATX Case", "price": 100, "type": "Case", "watt": 0},
    {"name": "Enthusiast Full Tower", "price": 180, "type": "Case", "watt": 0},
    {"name": "500W PSU", "price": 50, "type": "PSU", "watt_limit": 500},
    {"name": "650W PSU", "price": 75, "type": "PSU", "watt_limit": 650},
    {"name": "750W PSU", "price": 90, "type": "PSU", "watt_limit": 750},
    {"name": "850W PSU", "price": 120, "type": "PSU", "watt_limit": 850},
    {"name": "1000W PSU", "price": 160, "type": "PSU", "watt_limit": 1000},
    {"name": "1200W PSU", "price": 220, "type": "PSU", "watt_limit": 1200},
]
